create table hobby (
                       name  varchar(40) primary key,
                       link  varchar(100),
                       category varchar(40),
                       in_out varchar(10)
);

INSERT INTO hobby VALUES ('3D printing','https://en.wikipedia.org/wiki/3D_printing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Acrobatics','https://en.wikipedia.org/wiki/Acrobatics','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Acting','https://en.wikipedia.org/wiki/Acting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Amateur radio','https://en.wikipedia.org/wiki/Amateur_radio','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Animation','https://en.wikipedia.org/wiki/Animation','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Aquascaping','https://en.wikipedia.org/wiki/Aquascaping','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Astrology','https://en.wikipedia.org/wiki/Astrology','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Baking','https://en.wikipedia.org/wiki/Baking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Baton twirling','https://en.wikipedia.org/wiki/Baton_twirling','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Blogging','https://en.wikipedia.org/wiki/Blogging','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Board game','https://en.wikipedia.org/wiki/Board_game','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Book discussion club','https://en.wikipedia.org/wiki/Book_discussion_club','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Book restoration','https://en.wikipedia.org/wiki/Book_restoration','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Bowling','https://en.wikipedia.org/wiki/Bowling','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Brazilian jiu-jitsu','https://en.wikipedia.org/wiki/Brazilian_jiu-jitsu','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Breadmaking','https://en.wikipedia.org/wiki/Breadmaking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Building','https://en.wikipedia.org/wiki/Building','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Bullet Journal','https://en.wikipedia.org/wiki/Bullet_Journal','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Cabaret','https://en.wikipedia.org/wiki/Cabaret','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Calligraphy','https://en.wikipedia.org/wiki/Calligraphy','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Candle making','https://en.wikipedia.org/wiki/Candle_making','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Candy making','https://en.wikipedia.org/wiki/Candy_making','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Car','https://en.wikipedia.org/wiki/Car','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Card games','https://en.wikipedia.org/wiki/Card_games','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Cardistry','https://en.wikipedia.org/wiki/Cardistry','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Cheesemaking','https://en.wikipedia.org/wiki/Cheesemaking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Cleaning','https://en.wikipedia.org/wiki/Cleaning','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Clothing','https://en.wikipedia.org/wiki/Clothing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Home roasting coffee','https://en.wikipedia.org/wiki/Home_roasting_coffee','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Collecting','https://en.wikipedia.org/wiki/Collecting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Coloring book','https://en.wikipedia.org/wiki/Coloring_book','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Computer programming','https://en.wikipedia.org/wiki/Computer_programming','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Confectionery','https://en.wikipedia.org/wiki/Confectionery','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Cooking','https://en.wikipedia.org/wiki/Cooking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Cosplaying','https://en.wikipedia.org/wiki/Cosplaying','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Couponing','https://en.wikipedia.org/wiki/Couponing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Craft','https://en.wikipedia.org/wiki/Craft','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Creative writing','https://en.wikipedia.org/wiki/Creative_writing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Crocheting','https://en.wikipedia.org/wiki/Crocheting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Cross-stitch','https://en.wikipedia.org/wiki/Cross-stitch','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Crossword puzzles','https://en.wikipedia.org/wiki/Crossword_puzzles','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Cryptography','https://en.wikipedia.org/wiki/Cryptography','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Cue sports','https://en.wikipedia.org/wiki/Cue_sports','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Dance','https://en.wikipedia.org/wiki/Dance','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Digital art','https://en.wikipedia.org/wiki/Digital_art','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Distro-hopping','https://en.wikipedia.org/wiki/Distro-hopping','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Disc-jockey','https://en.wikipedia.org/wiki/Disc-jockey','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Do it yourself','https://en.wikipedia.org/wiki/Do_it_yourself','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Drama','https://en.wikipedia.org/wiki/Drama','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Drawing','https://en.wikipedia.org/wiki/Drawing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Mixed drink','https://en.wikipedia.org/wiki/Mixed_drink','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Drinking','https://en.wikipedia.org/wiki/Drinking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Electronic games','https://en.wikipedia.org/wiki/Electronic_games','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Electronics','https://en.wikipedia.org/wiki/Electronics','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Embroidery','https://en.wikipedia.org/wiki/Embroidery','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Experimenting','https://en.wikipedia.org/wiki/Experimenting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Fantasy sport','https://en.wikipedia.org/wiki/Fantasy_sport','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Fashion','https://en.wikipedia.org/wiki/Fashion','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Fashion design','https://en.wikipedia.org/wiki/Fashion_design','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Fishkeeping','https://en.wikipedia.org/wiki/Fishkeeping','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Filmmaking','https://en.wikipedia.org/wiki/Filmmaking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Flower arranging','https://en.wikipedia.org/wiki/Flower_arranging','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Fly tying','https://en.wikipedia.org/wiki/Fly_tying','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Second-language acquisition','https://en.wikipedia.org/wiki/Second-language_acquisition','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Furniture','https://en.wikipedia.org/wiki/Furniture','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Games','https://en.wikipedia.org/wiki/Games','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Tabletop game','https://en.wikipedia.org/wiki/Tabletop_game','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Role-playing game','https://en.wikipedia.org/wiki/Role-playing_game','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Genealogy','https://en.wikipedia.org/wiki/Genealogy','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Gingerbread house','https://en.wikipedia.org/wiki/Gingerbread_house','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Glassblowing','https://en.wikipedia.org/wiki/Glassblowing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Graphic design','https://en.wikipedia.org/wiki/Graphic_design','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Gunsmithing','https://en.wikipedia.org/wiki/Gunsmithing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Gymnastics','https://en.wikipedia.org/wiki/Gymnastics','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Hacker','https://en.wikipedia.org/wiki/Hacker','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Herpetoculture','https://en.wikipedia.org/wiki/Herpetoculture','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Home improvement','https://en.wikipedia.org/wiki/Home_improvement','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Homebrewing','https://en.wikipedia.org/wiki/Homebrewing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Houseplant care','https://en.wikipedia.org/wiki/Houseplant_care','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Hula hooping','https://en.wikipedia.org/wiki/Hula_hooping','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Humor','https://en.wikipedia.org/wiki/Humor','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Hydroponics','https://en.wikipedia.org/wiki/Hydroponics','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Ice skating','https://en.wikipedia.org/wiki/Ice_skating','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Jewelry making','https://en.wikipedia.org/wiki/Jewelry_making','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Jigsaw puzzles','https://en.wikipedia.org/wiki/Jigsaw_puzzles','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Diary','https://en.wikipedia.org/wiki/Diary','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Juggling','https://en.wikipedia.org/wiki/Juggling','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Karaoke','https://en.wikipedia.org/wiki/Karaoke','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Karate','https://en.wikipedia.org/wiki/Karate','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Kendama','https://en.wikipedia.org/wiki/Kendama','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Knife making','https://en.wikipedia.org/wiki/Knife_making','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Knitting','https://en.wikipedia.org/wiki/Knitting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Knot tying','https://en.wikipedia.org/wiki/Knot_tying','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Kombucha','https://en.wikipedia.org/wiki/Kombucha','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Lace making','https://en.wikipedia.org/wiki/Lace_making','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Lapidary','https://en.wikipedia.org/wiki/Lapidary','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Leather crafting','https://en.wikipedia.org/wiki/Leather_crafting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Lego','https://en.wikipedia.org/wiki/Lego','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Music','https://en.wikipedia.org/wiki/Music','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Podcasts','https://en.wikipedia.org/wiki/Podcasts','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Lock picking','https://en.wikipedia.org/wiki/Lock_picking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Machining','https://en.wikipedia.org/wiki/Machining','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Macrame','https://en.wikipedia.org/wiki/Macrame','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Magic (illusion)','https://en.wikipedia.org/wiki/Magic_(illusion)','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Makeup','https://en.wikipedia.org/wiki/Makeup','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Maze','https://en.wikipedia.org/wiki/Maze','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Metalworking','https://en.wikipedia.org/wiki/Metalworking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Model building','https://en.wikipedia.org/wiki/Model_building','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Model engineering','https://en.wikipedia.org/wiki/Model_engineering','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Nail art','https://en.wikipedia.org/wiki/Nail_art','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Needlepoint','https://en.wikipedia.org/wiki/Needlepoint','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Origami','https://en.wikipedia.org/wiki/Origami','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Painting','https://en.wikipedia.org/wiki/Painting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Palmistry','https://en.wikipedia.org/wiki/Palmistry','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Pet adoption','https://en.wikipedia.org/wiki/Pet_adoption','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Philately','https://en.wikipedia.org/wiki/Philately','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Photography','https://en.wikipedia.org/wiki/Photography','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Pilates','https://en.wikipedia.org/wiki/Pilates','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Music','https://en.wikipedia.org/wiki/Music','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Poi (performance art)','https://en.wikipedia.org/wiki/Poi_(performance_art)','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Pole Dancing (page does not exist)','https://en.wikipedia.org/w/index.php?title=Pole_Dancing&action=edit&redlink=1','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Pottery','https://en.wikipedia.org/wiki/Pottery','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Powerlifting','https://en.wikipedia.org/wiki/Powerlifting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Practical jokes','https://en.wikipedia.org/wiki/Practical_jokes','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Pressed flower craft','https://en.wikipedia.org/wiki/Pressed_flower_craft','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Puzzle','https://en.wikipedia.org/wiki/Puzzle','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Quilling','https://en.wikipedia.org/wiki/Quilling','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Quilting','https://en.wikipedia.org/wiki/Quilting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Quizzes','https://en.wikipedia.org/wiki/Quizzes','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Radio-controlled model','https://en.wikipedia.org/wiki/Radio-controlled_model','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Rail transport modeling','https://en.wikipedia.org/wiki/Rail_transport_modeling','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Rapping','https://en.wikipedia.org/wiki/Rapping','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Reading','https://en.wikipedia.org/wiki/Reading','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Refinishing','https://en.wikipedia.org/wiki/Refinishing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Reiki','https://en.wikipedia.org/wiki/Reiki','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Robot combat','https://en.wikipedia.org/wiki/Robot_combat','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Rubiks Cube','https://en.wikipedia.org/wiki/Rubik%27s_Cube','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Scrapbooking','https://en.wikipedia.org/wiki/Scrapbooking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('SCUBA Diving','https://en.wikipedia.org/wiki/SCUBA_Diving','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Sculpting','https://en.wikipedia.org/wiki/Sculpting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Sewing','https://en.wikipedia.org/wiki/Sewing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Shoemaking','https://en.wikipedia.org/wiki/Shoemaking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Singing','https://en.wikipedia.org/wiki/Singing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Sketch (drawing)','https://en.wikipedia.org/wiki/Sketch_(drawing)','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Skipping rope','https://en.wikipedia.org/wiki/Skipping_rope','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Slot car','https://en.wikipedia.org/wiki/Slot_car','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Soapmaking','https://en.wikipedia.org/wiki/Soapmaking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Social media','https://en.wikipedia.org/wiki/Social_media','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Spreadsheets','https://en.wikipedia.org/wiki/Spreadsheets','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Stand-up comedy','https://en.wikipedia.org/wiki/Stand-up_comedy','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Stamp collecting','https://en.wikipedia.org/wiki/Stamp_collecting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Table tennis','https://en.wikipedia.org/wiki/Table_tennis','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Tarot','https://en.wikipedia.org/wiki/Tarot','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Taxidermy','https://en.wikipedia.org/wiki/Taxidermy','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Charity shop','https://en.wikipedia.org/wiki/Charity_shop','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Video editing','https://en.wikipedia.org/wiki/Video_editing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Video game development','https://en.wikipedia.org/wiki/Video_game_development','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Video gaming','https://en.wikipedia.org/wiki/Video_gaming','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Videography','https://en.wikipedia.org/wiki/Videography','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Virtual reality','https://en.wikipedia.org/wiki/Virtual_reality','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Movies','https://en.wikipedia.org/wiki/Movies','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Television program','https://en.wikipedia.org/wiki/Television_program','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Waxing','https://en.wikipedia.org/wiki/Waxing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Weaving','https://en.wikipedia.org/wiki/Weaving','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Webtoon','https://en.wikipedia.org/wiki/Webtoon','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Weight training','https://en.wikipedia.org/wiki/Weight_training','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Welding','https://en.wikipedia.org/wiki/Welding','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Whittling','https://en.wikipedia.org/wiki/Whittling','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Help:Editing','https://en.wikipedia.org/wiki/Help:Editing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Winemaking','https://en.wikipedia.org/wiki/Winemaking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Wood carving','https://en.wikipedia.org/wiki/Wood_carving','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Woodworking','https://en.wikipedia.org/wiki/Woodworking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Word searches','https://en.wikipedia.org/wiki/Word_searches','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Worldbuilding','https://en.wikipedia.org/wiki/Worldbuilding','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Writing','https://en.wikipedia.org/wiki/Writing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Yo-yoing','https://en.wikipedia.org/wiki/Yo-yoing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Yoga','https://en.wikipedia.org/wiki/Yoga','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Zumba','https://en.wikipedia.org/wiki/Zumba','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Air sports','https://en.wikipedia.org/wiki/Air_sports','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Airsoft','https://en.wikipedia.org/wiki/Airsoft','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Amateur geology','https://en.wikipedia.org/wiki/Amateur_geology','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Amusement park','https://en.wikipedia.org/wiki/Amusement_park','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Archery','https://en.wikipedia.org/wiki/Archery','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Astronomy','https://en.wikipedia.org/wiki/Astronomy','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Backpacking (wilderness)','https://en.wikipedia.org/wiki/Backpacking_(wilderness)','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Badminton','https://en.wikipedia.org/wiki/Badminton','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('BASE jumping','https://en.wikipedia.org/wiki/BASE_jumping','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Baseball','https://en.wikipedia.org/wiki/Baseball','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Basketball','https://en.wikipedia.org/wiki/Basketball','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Beekeeping','https://en.wikipedia.org/wiki/Beekeeping','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Birdwatching','https://en.wikipedia.org/wiki/Birdwatching','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Blacksmithing','https://en.wikipedia.org/wiki/Blacksmithing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('BMX','https://en.wikipedia.org/wiki/BMX','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Board sports','https://en.wikipedia.org/wiki/Board_sports','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Bodybuilding','https://en.wikipedia.org/wiki/Bodybuilding','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Bonsai','https://en.wikipedia.org/wiki/Bonsai','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Butterfly watching','https://en.wikipedia.org/wiki/Butterfly_watching','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Bus','https://en.wikipedia.org/wiki/Bus','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Camping','https://en.wikipedia.org/wiki/Camping','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Canoeing','https://en.wikipedia.org/wiki/Canoeing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Canyoning','https://en.wikipedia.org/wiki/Canyoning','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Car','https://en.wikipedia.org/wiki/Car','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Caving','https://en.wikipedia.org/wiki/Caving','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Composting','https://en.wikipedia.org/wiki/Composting','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Cycling','https://en.wikipedia.org/wiki/Cycling','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Dowsing','https://en.wikipedia.org/wiki/Dowsing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Driving','https://en.wikipedia.org/wiki/Driving','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Farming','https://en.wikipedia.org/wiki/Farming','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Fishing','https://en.wikipedia.org/wiki/Fishing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Flag football','https://en.wikipedia.org/wiki/Flag_football','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Flower','https://en.wikipedia.org/wiki/Flower','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Aviation','https://en.wikipedia.org/wiki/Aviation','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Flying disc','https://en.wikipedia.org/wiki/Flying_disc','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Foraging','https://en.wikipedia.org/wiki/Foraging','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Fossicking','https://en.wikipedia.org/wiki/Fossicking','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Freestyle football','https://en.wikipedia.org/wiki/Freestyle_football','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Gardening','https://en.wikipedia.org/wiki/Gardening','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Geocaching','https://en.wikipedia.org/wiki/Geocaching','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Ghost hunting','https://en.wikipedia.org/wiki/Ghost_hunting','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Gold prospecting','https://en.wikipedia.org/wiki/Gold_prospecting','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Graffiti','https://en.wikipedia.org/wiki/Graffiti','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Handball','https://en.wikipedia.org/wiki/Handball','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Herbalism','https://en.wikipedia.org/wiki/Herbalism','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Herping','https://en.wikipedia.org/wiki/Herping','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('High-power rocketry','https://en.wikipedia.org/wiki/High-power_rocketry','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Hiking','https://en.wikipedia.org/wiki/Hiking','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Hobby horse','https://en.wikipedia.org/wiki/Hobby_horse','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Hobby tunneling','https://en.wikipedia.org/wiki/Hobby_tunneling','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Hooping','https://en.wikipedia.org/wiki/Hooping','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Horseback riding','https://en.wikipedia.org/wiki/Horseback_riding','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Hunting','https://en.wikipedia.org/wiki/Hunting','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Inline skating','https://en.wikipedia.org/wiki/Inline_skating','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Jogging','https://en.wikipedia.org/wiki/Jogging','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Jumping rope','https://en.wikipedia.org/wiki/Jumping_rope','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Kayaking','https://en.wikipedia.org/wiki/Kayaking','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Kite','https://en.wikipedia.org/wiki/Kite','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Kitesurfing','https://en.wikipedia.org/wiki/Kitesurfing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Lacrosse','https://en.wikipedia.org/wiki/Lacrosse','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('LARPing','https://en.wikipedia.org/wiki/LARPing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Letterboxing (hobby)','https://en.wikipedia.org/wiki/Letterboxing_(hobby)','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Longboarding','https://en.wikipedia.org/wiki/Longboarding','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Martial arts','https://en.wikipedia.org/wiki/Martial_arts','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Metal detector','https://en.wikipedia.org/wiki/Metal_detector','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Meteorology','https://en.wikipedia.org/wiki/Meteorology','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Motor sports','https://en.wikipedia.org/wiki/Motor_sports','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Mountain biking','https://en.wikipedia.org/wiki/Mountain_biking','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Mountaineering','https://en.wikipedia.org/wiki/Mountaineering','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Museum','https://en.wikipedia.org/wiki/Museum','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Mushroom hunting','https://en.wikipedia.org/wiki/Mushroom_hunting','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Mycology','https://en.wikipedia.org/wiki/Mycology','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Netball','https://en.wikipedia.org/wiki/Netball','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Nordic skating','https://en.wikipedia.org/wiki/Nordic_skating','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Orienteering','https://en.wikipedia.org/wiki/Orienteering','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Paintball','https://en.wikipedia.org/wiki/Paintball','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Parkour','https://en.wikipedia.org/wiki/Parkour','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Photography','https://en.wikipedia.org/wiki/Photography','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Podcast','https://en.wikipedia.org/wiki/Podcast','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Polo','https://en.wikipedia.org/wiki/Polo','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Public transport','https://en.wikipedia.org/wiki/Public_transport','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Rafting','https://en.wikipedia.org/wiki/Rafting','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Railway','https://en.wikipedia.org/wiki/Railway','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Rappelling','https://en.wikipedia.org/wiki/Rappelling','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Road Cycling','https://en.wikipedia.org/wiki/Road_Cycling','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Rock climbing','https://en.wikipedia.org/wiki/Rock_climbing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Roller skating','https://en.wikipedia.org/wiki/Roller_skating','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Rugby football','https://en.wikipedia.org/wiki/Rugby_football','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Running','https://en.wikipedia.org/wiki/Running','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Radio-controlled model','https://en.wikipedia.org/wiki/Radio-controlled_model','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Sailing','https://en.wikipedia.org/wiki/Sailing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Sand art and play','https://en.wikipedia.org/wiki/Sand_art_and_play','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Scouting','https://en.wikipedia.org/wiki/Scouting','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Scuba diving','https://en.wikipedia.org/wiki/Scuba_diving','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Sculling','https://en.wikipedia.org/wiki/Sculling','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Rowing (sport)','https://en.wikipedia.org/wiki/Rowing_(sport)','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Shooting','https://en.wikipedia.org/wiki/Shooting','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Shopping','https://en.wikipedia.org/wiki/Shopping','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Shuffleboard','https://en.wikipedia.org/wiki/Shuffleboard','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Skateboarding','https://en.wikipedia.org/wiki/Skateboarding','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Skiing','https://en.wikipedia.org/wiki/Skiing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Skimboarding','https://en.wikipedia.org/wiki/Skimboarding','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Skydiving','https://en.wikipedia.org/wiki/Skydiving','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Slacklining','https://en.wikipedia.org/wiki/Slacklining','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Snowboarding','https://en.wikipedia.org/wiki/Snowboarding','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Snowmobiling','https://en.wikipedia.org/wiki/Snowmobiling','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Snowshoeing','https://en.wikipedia.org/wiki/Snowshoeing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Soccer','https://en.wikipedia.org/wiki/Soccer','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Stone skipping','https://en.wikipedia.org/wiki/Stone_skipping','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Sun bathing','https://en.wikipedia.org/wiki/Sun_bathing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Surfing','https://en.wikipedia.org/wiki/Surfing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Survivalism','https://en.wikipedia.org/wiki/Survivalism','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Human swimming','https://en.wikipedia.org/wiki/Human_swimming','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Taekwondo','https://en.wikipedia.org/wiki/Taekwondo','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Tai chi','https://en.wikipedia.org/wiki/Tai_chi','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Tennis','https://en.wikipedia.org/wiki/Tennis','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Topiary','https://en.wikipedia.org/wiki/Topiary','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Tourism','https://en.wikipedia.org/wiki/Tourism','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Thru-hiking','https://en.wikipedia.org/wiki/Thru-hiking','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Trade fair','https://en.wikipedia.org/wiki/Trade_fair','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Travel','https://en.wikipedia.org/wiki/Travel','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Urban exploration','https://en.wikipedia.org/wiki/Urban_exploration','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Vacation','https://en.wikipedia.org/wiki/Vacation','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Vegetable farming','https://en.wikipedia.org/wiki/Vegetable_farming','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Videography','https://en.wikipedia.org/wiki/Videography','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Vehicle restoration','https://en.wikipedia.org/wiki/Vehicle_restoration','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Walking','https://en.wikipedia.org/wiki/Walking','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Water sports','https://en.wikipedia.org/wiki/Water_sports','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Astronomy','https://en.wikipedia.org/wiki/Astronomy','Educational hobbies','---');
INSERT INTO hobby VALUES ('Biology','https://en.wikipedia.org/wiki/Biology','Educational hobbies','---');
INSERT INTO hobby VALUES ('Chemistry','https://en.wikipedia.org/wiki/Chemistry','Educational hobbies','---');
INSERT INTO hobby VALUES ('Electrochemistry','https://en.wikipedia.org/wiki/Electrochemistry','Educational hobbies','---');
INSERT INTO hobby VALUES ('Geography','https://en.wikipedia.org/wiki/Geography','Educational hobbies','---');
INSERT INTO hobby VALUES ('History','https://en.wikipedia.org/wiki/History','Educational hobbies','---');
INSERT INTO hobby VALUES ('Mathematics','https://en.wikipedia.org/wiki/Mathematics','Educational hobbies','---');
INSERT INTO hobby VALUES ('Psychology','https://en.wikipedia.org/wiki/Psychology','Educational hobbies','---');
INSERT INTO hobby VALUES ('Physics','https://en.wikipedia.org/wiki/Physics','Educational hobbies','---');
INSERT INTO hobby VALUES ('Rail transport','https://en.wikipedia.org/wiki/Rail_transport','Educational hobbies','---');
INSERT INTO hobby VALUES ('Science and technology studies','https://en.wikipedia.org/wiki/Science_and_technology_studies','Educational hobbies','---');
INSERT INTO hobby VALUES ('Social studies','https://en.wikipedia.org/wiki/Social_studies','Educational hobbies','---');
INSERT INTO hobby VALUES ('Sports science','https://en.wikipedia.org/wiki/Sports_science','Educational hobbies','---');
INSERT INTO hobby VALUES ('Action figure','https://en.wikipedia.org/wiki/Action_figure','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Antiquing','https://en.wikipedia.org/wiki/Antiquing','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Ant-keeping','https://en.wikipedia.org/wiki/Ant-keeping','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Art collecting','https://en.wikipedia.org/wiki/Art_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Book collecting','https://en.wikipedia.org/wiki/Book_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Button collecting','https://en.wikipedia.org/wiki/Button_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Trading cards','https://en.wikipedia.org/wiki/Trading_cards','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Coin collecting','https://en.wikipedia.org/wiki/Coin_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Comic book collecting','https://en.wikipedia.org/wiki/Comic_book_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Deltiology','https://en.wikipedia.org/wiki/Deltiology','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Die-cast toy','https://en.wikipedia.org/wiki/Die-cast_toy','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Digital hoarding','https://en.wikipedia.org/wiki/Digital_hoarding','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Dolls','https://en.wikipedia.org/wiki/Dolls','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Element collecting','https://en.wikipedia.org/wiki/Element_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Ephemera','https://en.wikipedia.org/wiki/Ephemera','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Telephone card','https://en.wikipedia.org/wiki/Telephone_card','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Knife collecting','https://en.wikipedia.org/wiki/Knife_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Lotology','https://en.wikipedia.org/wiki/Lotology','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Film memorabilia','https://en.wikipedia.org/wiki/Film_memorabilia','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Fingerprint','https://en.wikipedia.org/wiki/Fingerprint','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Perfume','https://en.wikipedia.org/wiki/Perfume','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Phillumeny','https://en.wikipedia.org/wiki/Phillumeny','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Radio-controlled model','https://en.wikipedia.org/wiki/Radio-controlled_model','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Rail transport modelling','https://en.wikipedia.org/wiki/Rail_transport_modelling','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Record collecting','https://en.wikipedia.org/wiki/Record_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Rock tumbling','https://en.wikipedia.org/wiki/Rock_tumbling','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Patch collecting','https://en.wikipedia.org/wiki/Patch_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Shoes','https://en.wikipedia.org/wiki/Shoes','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Slot car','https://en.wikipedia.org/wiki/Slot_car','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Sports memorabilia','https://en.wikipedia.org/wiki/Sports_memorabilia','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Stamp collecting','https://en.wikipedia.org/wiki/Stamp_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Stuffed toy','https://en.wikipedia.org/wiki/Stuffed_toy','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Tea bag','https://en.wikipedia.org/wiki/Tea_bag','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Ticket (admission)','https://en.wikipedia.org/wiki/Ticket_(admission)','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Toys','https://en.wikipedia.org/wiki/Toys','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Transit map','https://en.wikipedia.org/wiki/Transit_map','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Video game collecting','https://en.wikipedia.org/wiki/Video_game_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Vintage cars','https://en.wikipedia.org/wiki/Vintage_cars','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Vintage clothing','https://en.wikipedia.org/wiki/Vintage_clothing','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Vinyl Records','https://en.wikipedia.org/wiki/Vinyl_Records','Samler hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Antiquities','https://en.wikipedia.org/wiki/Antiquities','Samler hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Auto audiophilia','https://en.wikipedia.org/wiki/Auto_audiophilia','Samler hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Pressed flower craft','https://en.wikipedia.org/wiki/Pressed_flower_craft','Samler hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Fossil hunting','https://en.wikipedia.org/wiki/Fossil_hunting','Samler hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Insect collecting','https://en.wikipedia.org/wiki/Insect_collecting','Samler hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Magnet fishing','https://en.wikipedia.org/wiki/Magnet_fishing','Samler hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Metal detecting','https://en.wikipedia.org/wiki/Metal_detecting','Samler hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Mineral collecting','https://en.wikipedia.org/wiki/Mineral_collecting','Samler hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Rock balancing','https://en.wikipedia.org/wiki/Rock_balancing','Samler hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Sea glass','https://en.wikipedia.org/wiki/Sea_glass','Samler hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Seashell','https://en.wikipedia.org/wiki/Seashell','Samler hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Stone collecting','https://en.wikipedia.org/wiki/Stone_collecting','Samler hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Animal fancy','https://en.wikipedia.org/wiki/Animal_fancy','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Axe throwing','https://en.wikipedia.org/wiki/Axe_throwing','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Backgammon','https://en.wikipedia.org/wiki/Backgammon','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Badminton','https://en.wikipedia.org/wiki/Badminton','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Baton twirling','https://en.wikipedia.org/wiki/Baton_twirling','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Beauty pageant','https://en.wikipedia.org/wiki/Beauty_pageant','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Cue sports','https://en.wikipedia.org/wiki/Cue_sports','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Bowling','https://en.wikipedia.org/wiki/Bowling','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Boxing','https://en.wikipedia.org/wiki/Boxing','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Contract Bridge','https://en.wikipedia.org/wiki/Contract_Bridge','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Draughts','https://en.wikipedia.org/wiki/Draughts','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Cheerleading','https://en.wikipedia.org/wiki/Cheerleading','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Chess','https://en.wikipedia.org/wiki/Chess','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Color guard (flag spinning)','https://en.wikipedia.org/wiki/Color_guard_(flag_spinning)','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Cribbage','https://en.wikipedia.org/wiki/Cribbage','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Curling','https://en.wikipedia.org/wiki/Curling','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Competitive dance','https://en.wikipedia.org/wiki/Competitive_dance','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Darts','https://en.wikipedia.org/wiki/Darts','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Debate','https://en.wikipedia.org/wiki/Debate','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Dominoes','https://en.wikipedia.org/wiki/Dominoes','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Competitive eating','https://en.wikipedia.org/wiki/Competitive_eating','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Esports','https://en.wikipedia.org/wiki/Esports','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Fencing','https://en.wikipedia.org/wiki/Fencing','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Go (game)','https://en.wikipedia.org/wiki/Go_(game)','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Gymnastics','https://en.wikipedia.org/wiki/Gymnastics','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Ice hockey','https://en.wikipedia.org/wiki/Ice_hockey','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Ice skating','https://en.wikipedia.org/wiki/Ice_skating','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Judo','https://en.wikipedia.org/wiki/Judo','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Jujitsu','https://en.wikipedia.org/wiki/Jujitsu','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Kabaddi','https://en.wikipedia.org/wiki/Kabaddi','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Word games','https://en.wikipedia.org/wiki/Word_games','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Laser tag','https://en.wikipedia.org/wiki/Laser_tag','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Longboarding','https://en.wikipedia.org/wiki/Longboarding','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Mahjong','https://en.wikipedia.org/wiki/Mahjong','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Marbles','https://en.wikipedia.org/wiki/Marbles','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Martial arts','https://en.wikipedia.org/wiki/Martial_arts','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Model United Nations','https://en.wikipedia.org/wiki/Model_United_Nations','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Poker','https://en.wikipedia.org/wiki/Poker','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Pole Dancing (page does not exist)','https://en.wikipedia.org/w/index.php?title=Pole_Dancing&action=edit&redlink=1','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Pool (cue sports)','https://en.wikipedia.org/wiki/Pool_(cue_sports)','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Role-playing games','https://en.wikipedia.org/wiki/Role-playing_games','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Shogi','https://en.wikipedia.org/wiki/Shogi','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Slot car racing','https://en.wikipedia.org/wiki/Slot_car_racing','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Speedcubing','https://en.wikipedia.org/wiki/Speedcubing','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Sport stacking','https://en.wikipedia.org/wiki/Sport_stacking','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Table football','https://en.wikipedia.org/wiki/Table_football','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Table tennis','https://en.wikipedia.org/wiki/Table_tennis','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Volleyball','https://en.wikipedia.org/wiki/Volleyball','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Weight training','https://en.wikipedia.org/wiki/Weight_training','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Wrestling','https://en.wikipedia.org/wiki/Wrestling','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Airsoft','https://en.wikipedia.org/wiki/Airsoft','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Archery','https://en.wikipedia.org/wiki/Archery','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Association football','https://en.wikipedia.org/wiki/Association_football','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Australian rules football','https://en.wikipedia.org/wiki/Australian_rules_football','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Auto racing','https://en.wikipedia.org/wiki/Auto_racing','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Baseball','https://en.wikipedia.org/wiki/Baseball','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Beach volleyball','https://en.wikipedia.org/wiki/Beach_volleyball','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Breakdancing','https://en.wikipedia.org/wiki/Breakdancing','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Climbing','https://en.wikipedia.org/wiki/Climbing','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Cricket','https://en.wikipedia.org/wiki/Cricket','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Croquet','https://en.wikipedia.org/wiki/Croquet','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Cycling','https://en.wikipedia.org/wiki/Cycling','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Disc golf','https://en.wikipedia.org/wiki/Disc_golf','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Dog sport','https://en.wikipedia.org/wiki/Dog_sport','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Equestrianism','https://en.wikipedia.org/wiki/Equestrianism','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Exhibition drill','https://en.wikipedia.org/wiki/Exhibition_drill','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Field hockey','https://en.wikipedia.org/wiki/Field_hockey','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Figure skating','https://en.wikipedia.org/wiki/Figure_skating','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Fishing','https://en.wikipedia.org/wiki/Fishing','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Footbag','https://en.wikipedia.org/wiki/Footbag','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Frisbee','https://en.wikipedia.org/wiki/Frisbee','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Golf','https://en.wikipedia.org/wiki/Golf','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Handball','https://en.wikipedia.org/wiki/Handball','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Horseback riding','https://en.wikipedia.org/wiki/Horseback_riding','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Horseshoes','https://en.wikipedia.org/wiki/Horseshoes','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Iceboat','https://en.wikipedia.org/wiki/Iceboat','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Jukskei','https://en.wikipedia.org/wiki/Jukskei','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Kart racing','https://en.wikipedia.org/wiki/Kart_racing','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Knife throwing','https://en.wikipedia.org/wiki/Knife_throwing','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Lacrosse','https://en.wikipedia.org/wiki/Lacrosse','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Longboarding','https://en.wikipedia.org/wiki/Longboarding','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Long-distance running','https://en.wikipedia.org/wiki/Long-distance_running','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Marching band','https://en.wikipedia.org/wiki/Marching_band','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Model aircraft','https://en.wikipedia.org/wiki/Model_aircraft','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Orienteering','https://en.wikipedia.org/wiki/Orienteering','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Pickleball','https://en.wikipedia.org/wiki/Pickleball','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Quidditch (sport)','https://en.wikipedia.org/wiki/Quidditch_(sport)','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Race walking','https://en.wikipedia.org/wiki/Race_walking','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Racquetball','https://en.wikipedia.org/wiki/Racquetball','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Radio-controlled car','https://en.wikipedia.org/wiki/Radio-controlled_car','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Roller derby','https://en.wikipedia.org/wiki/Roller_derby','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Rugby league','https://en.wikipedia.org/wiki/Rugby_league','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Sculling','https://en.wikipedia.org/wiki/Sculling','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Rowing','https://en.wikipedia.org/wiki/Rowing','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Shooting sport','https://en.wikipedia.org/wiki/Shooting_sport','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Skateboarding','https://en.wikipedia.org/wiki/Skateboarding','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Skiing','https://en.wikipedia.org/wiki/Skiing','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Sled dog racing','https://en.wikipedia.org/wiki/Sled_dog_racing','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Softball','https://en.wikipedia.org/wiki/Softball','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Speed skating','https://en.wikipedia.org/wiki/Speed_skating','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Squash (sport)','https://en.wikipedia.org/wiki/Squash_(sport)','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Surfing','https://en.wikipedia.org/wiki/Surfing','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Human swimming','https://en.wikipedia.org/wiki/Human_swimming','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Table tennis','https://en.wikipedia.org/wiki/Table_tennis','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Tennis','https://en.wikipedia.org/wiki/Tennis','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Tennis polo','https://en.wikipedia.org/wiki/Tennis_polo','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Tether car','https://en.wikipedia.org/wiki/Tether_car','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Tour skating','https://en.wikipedia.org/wiki/Tour_skating','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Tourism','https://en.wikipedia.org/wiki/Tourism','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Trapshooting','https://en.wikipedia.org/wiki/Trapshooting','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Triathlon','https://en.wikipedia.org/wiki/Triathlon','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Ultimate (sport)','https://en.wikipedia.org/wiki/Ultimate_(sport)','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Volleyball','https://en.wikipedia.org/wiki/Volleyball','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Water polo','https://en.wikipedia.org/wiki/Water_polo','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Fishkeeping','https://en.wikipedia.org/wiki/Fishkeeping',' Observation hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Learning','https://en.wikipedia.org/wiki/Learning',' Observation hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Meditation','https://en.wikipedia.org/wiki/Meditation',' Observation hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Microscopy','https://en.wikipedia.org/wiki/Microscopy',' Observation hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Reading','https://en.wikipedia.org/wiki/Reading',' Observation hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Research','https://en.wikipedia.org/wiki/Research',' Observation hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Shortwave listening','https://en.wikipedia.org/wiki/Shortwave_listening',' Observation hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Audiophile','https://en.wikipedia.org/wiki/Audiophile',' Observation hobbyer','Indendørs');
INSERT INTO hobby VALUES ('Aircraft spotting','https://en.wikipedia.org/wiki/Aircraft_spotting',' Observation hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Amateur astronomy','https://en.wikipedia.org/wiki/Amateur_astronomy',' Observation hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Birdwatching','https://en.wikipedia.org/wiki/Birdwatching',' Observation hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Bus spotting','https://en.wikipedia.org/wiki/Bus_spotting',' Observation hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Geocaching','https://en.wikipedia.org/wiki/Geocaching',' Observation hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Gongoozler','https://en.wikipedia.org/wiki/Gongoozler',' Observation hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Herping','https://en.wikipedia.org/wiki/Herping',' Observation hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Hiking','https://en.wikipedia.org/wiki/Hiking',' Observation hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Backpacking (wilderness)','https://en.wikipedia.org/wiki/Backpacking_(wilderness)',' Observation hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Meteorology','https://en.wikipedia.org/wiki/Meteorology',' Observation hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Photography','https://en.wikipedia.org/wiki/Photography',' Observation hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Satellite watching','https://en.wikipedia.org/wiki/Satellite_watching',' Observation hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Trainspotting (hobby)','https://en.wikipedia.org/wiki/Trainspotting_(hobby)',' Observation hobbyer','Udendørs');
INSERT INTO hobby VALUES ('Whale watching','https://en.wikipedia.org/wiki/Whale_watching',' Observation hobbyer','Udendørs');